# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
app_home:
    path: /home
    controller: App\Controller\home::showTitle
app_login:
    path: /login
    controller: App\Controller\login::showTitle
app_register:
    path: /register
    controller: App\Controller\register::showTitle
app_card:
    path: /card
    controller: App\Controller\card::showTitle
app_catalog:
    path: /catalog
    controller: App\Controller\catalog::showTitle